# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE UI override any settings in this file.

# JVM Arguments
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Disable Configuration Cache to prevent CI/CD build failures
org.gradle.configuration-cache=false

# Non-transitive R classes
android.nonTransitiveRClass=true
